/******************************************************************************/
/***          Generated by IBExpert 2011.01.11 10.08.2011 6:59:57           ***/
/******************************************************************************/

/******************************************************************************/
/***      Following SET SQL DIALECT is just for the Database Comparer       ***/
/******************************************************************************/
SET SQL DIALECT 3;



/******************************************************************************/
/***                               Generators                               ***/
/******************************************************************************/

CREATE GENERATOR GEN_T_MONEY_OUT_ID;
CREATE GENERATOR GEN_T_MONEY_OUT_STR_ID;


/******************************************************************************/
/***                                 Tables                                 ***/
/******************************************************************************/



CREATE TABLE T_MONEY_OUT (
    F_ID       D_ID NOT NULL,
    F_SKLAD    D_INT,
    F_PARTNER  D_INT,
    F_BANK     D_INT,
    F_NUMBER   D_STR20,
    F_DATE     D_DATE,
    F_STATE    D_INT,
    F_SUMMA    D_FLOAT,
    F_TYPE     D_INT
);

CREATE TABLE T_MONEY_OUT_STR (
    F_ID     D_ID NOT NULL,
    F_DOC    D_INT,
    F_MONEY  D_INT,
    F_SUMMA  D_FLOAT
);



/******************************************************************************/
/***                              Primary Keys                              ***/
/******************************************************************************/

ALTER TABLE T_MONEY_OUT ADD CONSTRAINT PK_T_MONEY_OUT PRIMARY KEY (F_ID);
ALTER TABLE T_MONEY_OUT_STR ADD CONSTRAINT PK_T_MONEY_OUT_STR PRIMARY KEY (F_ID);


/******************************************************************************/
/***                              Foreign Keys                              ***/
/******************************************************************************/

ALTER TABLE T_MONEY_OUT ADD CONSTRAINT FK_T_MONEY_OUT_BANK FOREIGN KEY (F_BANK) REFERENCES T_NSI_BANK (F_ID);
ALTER TABLE T_MONEY_OUT ADD CONSTRAINT FK_T_MONEY_OUT_PARTNER FOREIGN KEY (F_PARTNER) REFERENCES T_NSI_PARTNER (F_ID);
ALTER TABLE T_MONEY_OUT ADD CONSTRAINT FK_T_MONEY_OUT_SKLAD FOREIGN KEY (F_SKLAD) REFERENCES T_NSI_SKLAD (F_ID);
ALTER TABLE T_MONEY_OUT ADD CONSTRAINT FK_T_MONEY_OUT_STATE FOREIGN KEY (F_STATE) REFERENCES T_NSI_STATE (F_ID);
ALTER TABLE T_MONEY_OUT ADD CONSTRAINT FK_T_MONEY_OUT_TYPES FOREIGN KEY (F_TYPE) REFERENCES T_NSI_MONEY_IN_TYPES (F_ID);
ALTER TABLE T_MONEY_OUT_STR ADD CONSTRAINT FK_T_MONEY_OUT_STR_DOC FOREIGN KEY (F_DOC) REFERENCES T_DOC_OUT (F_ID);


/******************************************************************************/
/***                                Indices                                 ***/
/******************************************************************************/

CREATE INDEX IDX_T_MONEY_OUT_DATE ON T_MONEY_OUT (F_DATE);
